### ISSUE TITLE
1. Dodanie klas:

### ISSUE THREAD

**Issue by Zeroooo-kun** [Zeroooo-kun/Praca-na-zajecia-narzedzia-informatyki#6]
-Stożek 
-Walec
-Kula

**Comment by KiraAmane** [comment]
[klasy.txt](https://github.com/Zeroooo-kun/Praca-na-zajecia-narzedzia-informatyki/files/4838552/klasy.txt)

**Comment by Zeroooo-kun** [comment]
Jest dobrze
