### ISSUE TITLE
2. Dodanie metod:

### ISSUE THREAD

**Issue by Zeroooo-kun** [Zeroooo-kun/Praca-na-zajecia-narzedzia-informatyki#7]
- metody pozwalające obliczyć objętość brył w nowych klasach

**Comment by KiraAmane** [comment]
[obliczanie objętości.txt](https://github.com/Zeroooo-kun/Praca-na-zajecia-narzedzia-informatyki/files/4839681/obliczanie.objetosci.txt)

**Comment by Zeroooo-kun** [comment]
okey
