### ISSUE TITLE
3. Dodanie obiektów do main

### ISSUE THREAD

**Issue by Zeroooo-kun** [Zeroooo-kun/Praca-na-zajecia-narzedzia-informatyki#8]
Dodanie obiektów do main dla nowo dodanych klas

**Comment by KiraAmane** [comment]
[obiekty.txt](https://github.com/Zeroooo-kun/Praca-na-zajecia-narzedzia-informatyki/files/4839683/obiekty.txt)

**Comment by Zeroooo-kun** [comment]
Dobra, jest w porządku.
